### ISSUE TITLE
Add support for ansible-navigator in homebrew

### ISSUE THREAD

**Issue by remyleone** [ansible/ansible-navigator#1863]
##### ISSUE TYPE

- Feature Idea

##### SUMMARY

As a macos user, I would like to install and update my software using a single package manager. Could you add support for ansible-navigator in homebrew?
If it is not accepted in the main repository, could you create a tap?

**Comment by ssbarnea** [comment]
While I use brew daily and love it, I am against this idea because the dependencies between navigator and all the other ansible tools. Use `pip` or `uv` to install it please, is a python project. Doing it would require 10+ other projects to also have brew recipes including ansible-core which does not have a brew recipe either!

Still, it could be interesting to create a recipe for ansible-dev-tools, which would include navigator. I would not be against, at least experimental to see how it goes.
