### ISSUE TITLE
ansible-launcher messes up with the user's terminal colorscheme

### ISSUE THREAD

**Issue by elyezer** [ansible/ansible-navigator#54]
Before running ansible-launcher:

![before-running](https://user-images.githubusercontent.com/48132/111329269-3cb35200-862c-11eb-9f34-a0224a35afa9.png)

Then run ansible-launcher and immediately quit:

![after-running](https://user-images.githubusercontent.com/48132/111329339-49d04100-862c-11eb-8304-54ddc0fa0ef2.png)

In order to restore the colorscheme I had to restart the terminal session.

I was using Windows Terminal and running ansible-launcher from an SSH connection to my Linux working laptop.

**Comment by cidrblock** [comment]
@elyezer Try running with `--osc4 false` this will disable ansible-navigators ability to change the terminal colors, I wonder if the terminal if misrepresenting it's osc4 ability as this issue doesn't exist on xterm

**Comment by cidrblock** [comment]
@elyezer anything to report here?

**Comment by elyezer** [comment]
I will have to try with the updated version. Will try to do it tomorrow. Sorry for the delay.

**Comment by cidrblock** [comment]
@elyezer thx, please keep us posted

**Comment by elyezer** [comment]
With the `--osc4 false` it works as expected. Also it seems to use the same colorscheme that it uses when `--osc4 true`. 

I found the issue while using Windows Terminal btw.

**Comment by cidrblock** [comment]
buried in the code, there is theme support, which is not user accessible yet (maybe v2), in order to do that we need the color changing support.

I suspect your terminal is misrepresenting it's OSC4 capability, which is why the colors weren't restored

The reason it still looks same, is the theme colors are mapped to your terminal colors, so it's going to be close with 256 color support, once you get to 16 or 8, the "best" color might not be a great match.

**Comment by cidrblock** [comment]
If you are interested in where all this happens, LMK.  I didn't want to flood the issue with code link, but it's some neat stuff IMO

**Comment by cidrblock** [comment]
Now covered in the FAQ https://github.com/ansible/ansible-navigator/blob/main/docs/faq.md
