### ISSUE TITLE
ansible-navigator artifacts don't contain EE image, args or runtime information

### ISSUE THREAD

**Issue by tonykay** [ansible/ansible-navigator#603]
For debugging and other purposes the log artifact created per run contains no information about the EE, name, tags, runtime, etc. So logs passed, for example, back to an SME, 3rd level support etc., lack encapsulated context. 

##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

Provide an extensive `execution-environment:` dictionary within the log so the exact context is captured. Useful attributes include:

- host OS
- container runtime (including version)
- EE name and tag
- CLI arguments.
- volume mounts
- extra vars

Goal: Anyone with the log should be able to exactly recreate the environment and test without additional files or context being supplied.

**Comment by cidrblock** [comment]
This should follow #577, as it should be able to reuse the generation of structured data from the configuration subsystem

**Comment by cidrblock** [comment]
@tonykay Because the collection of system and EE information would slow down the artifact creation, this was broken into 2 PRs.

The first adds the settings information to the artifact, that is all internal to ansible-navigator so it should have little if any impact on speed.
The second adds a `--diagnostics` flag to ansible-navigator that build a json file full of information about the local system and the configured execution environment, this takes about 5s to run.

Both are linked above and should be in 2.x when released.
