### ISSUE TITLE
[actions] Switch from `try/except` to a conditional import based on python version in `actions/_actions`

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-navigator#646]
This should eliminate the `# type ignore`

This should also wait until after CI has coverage for multiple python versions.

**Comment by webknjaz** [comment]
@ssbarnea do you remember the upstream mypy issue number for this?

**Comment by ssbarnea** [comment]
@cidrblock We do now have coverage reporting for all supported python versions. https://app.codecov.io/gh/ansible/ansible-navigator -- feel free to tacle this one.

**Comment by webknjaz** [comment]
This has been implemented last week with https://github.com/ansible/ansible-navigator/commit/d66e9987df1c134d4727f9edfd2de576ad1cf344, as a part of https://github.com/ansible/ansible-navigator/pull/765.

> the upstream mypy issue number for this?

The underlying issue is described @ https://github.com/ansible-community/ansible-lint/pull/915#discussion_r460154805 and https://github.com/python/typeshed/issues/3500#issuecomment-560958608
